# .goreleaser.yml
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
archive:
  format: binary
builds:
  - id: binary
    main: ./
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
dockers:
  -
    goos: linux
    goarch: amd64
    binaries:
    - mantle
    image_templates:
    - "ovotech/mantle:{{ .Tag }}"
    - "ovotech/mantle:v{{ .Major }}"
    - "ovotech/mantle:v{{ .Major }}.{{ .Minor }}"
    - "ovotech/mantle:latest"