defaults: &defaults
  working_directory: /go/src/github.com/ovotech/mantle

version: 2
jobs:
  goreleaser:
    <<: *defaults

    docker:
      - image: circleci/golang:1.10

    steps:
      - checkout

      - run:
           name: goreleaser
           command: |
             export GITHUB_TOKEN=$GITHUB
             curl -sL https://git.io/goreleaser | bash

  docker_build_and_push:
    <<: *defaults

    docker:
      - image: circleci/golang

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name:
          command: |
            export GO111MODULE=on
            go mod download
            GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build
            docker build -t ovotech/mantle:latest .
            echo $DOCKER_PASS | docker login -u=$DOCKER_USER --password-stdin
            docker push ovotech/mantle

  go_fmt:
    <<: *defaults

    docker:
    - image: eversc/go-pr-checks

    steps:
    - checkout

    - run:
        name: ensure gofmt
        command: |
          test -z $(gofmt -s -l $(find . -iname '*.go' -type f | grep -v /vendor/))
  go_vet:
    <<: *defaults

    docker:
    - image: eversc/go-pr-checks

    steps:
    - checkout

    - run:
        name: go vet
        command: go vet ./...

  go_cyclo:
    <<: *defaults

    docker:
    - image: eversc/go-pr-checks

    steps:
    - checkout

    - run:
        name: go_cyclo
        command: gocyclo -over 6 $(find . -iname '*.go' -type f | grep -v /vendor/)

  go_lint:
    <<: *defaults

    docker:
    - image: eversc/go-pr-checks

    steps:
    - checkout

    - run:
        name: golint
        command: golint -set_exit_status $(go list ./...)

  go_build:
    <<: *defaults

    docker:
    - image: eversc/go-pr-checks

    steps:
    - checkout

    - run:
        name: go build
        command: go build

workflows:
  version: 2
  goreleaser_pipeline:
    jobs:
      - goreleaser:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
            branches:
              ignore: /.*/
      - docker_build_and_push:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
            branches:
              ignore: /.*/
  pr_pipeline:
    jobs:
    - go_fmt:
        filters:
          branches:
            ignore: master
    - go_vet:
        filters:
          branches:
            ignore: master
    - go_cyclo:
        filters:
          branches:
            ignore: master
    - go_lint:
        filters:
          branches:
            ignore: master
    - go_build:
        filters:
          branches:
            ignore: master
