defaults: &defaults
  working_directory: /go/src/github.com/ovotech/mantle

version: 2
jobs:
  goreleaser:
    <<: *defaults

    docker:
      - image: cimg/go:1.18

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
           name: goreleaser
           command: |
             export GITHUB_TOKEN=$GITHUB
             echo $DOCKER_PASS | docker login -u=$DOCKER_USER --password-stdin
             curl -sL https://git.io/goreleaser | VERSION=v0.113.0 bash

  go_fmt:
    <<: *defaults

    docker:
    - image: eversc/go-pr-checks

    steps:
    - checkout

    - run:
        name: ensure gofmt
        command: |
          test -z $(gofmt -s -l $(find . -iname '*.go' -type f | grep -v /vendor/))
  go_vet:
    <<: *defaults

    docker:
    - image: eversc/go-pr-checks

    steps:
    - checkout

    - run:
        name: go vet
        command: go vet ./...

  go_cyclo:
    <<: *defaults

    docker:
    - image: eversc/go-pr-checks

    steps:
    - checkout

    - run:
        name: go_cyclo
        command: gocyclo -over 6 $(find . -iname '*.go' -type f | grep -v /vendor/)

  go_lint:
    <<: *defaults

    docker:
    - image: eversc/go-pr-checks

    steps:
    - checkout

    - run:
        name: golint
        command: golint -set_exit_status $(go list ./...)

  go_build:
    <<: *defaults

    docker:
    - image: eversc/go-pr-checks

    steps:
    - checkout

    - run:
        name: go build
        command: go build

  go_test:
    <<: *defaults

    docker:
      - image: eversc/go-pr-checks

    steps:
      - checkout

      - run:
           name: go test
           command: |
             echo $GCLOUD_SERVICE_KEY | base64 -d > /tmp/key.json
             export GOOGLE_APPLICATION_CREDENTIALS=/tmp/key.json
             go test ./... -v

  e2e_tests:
    docker:
      - image: cimg/go:1.18
    
    steps:
      - checkout

      - run:
            name: e2e tests
            command: |
              go build
              echo $GCLOUD_SERVICE_KEY | base64 -d > /tmp/key.json
              export GOOGLE_APPLICATION_CREDENTIALS=/tmp/key.json
              cd tests
              ./e2e-tests.sh

workflows:
  version: 2
  goreleaser_pipeline:
    jobs:
      - goreleaser:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
            branches:
              ignore: /.*/
  pr_pipeline:
    jobs:
    - go_fmt:
        filters:
          branches:
            ignore: master
    - go_vet:
        filters:
          branches:
            ignore: master
    - go_cyclo:
        filters:
          branches:
            ignore: master
    - go_lint:
        filters:
          branches:
            ignore: master
    - go_build:
        filters:
          branches:
            ignore: master
    - go_test:
        filters:
          branches:
            ignore: master
    - e2e_tests:
        filters:
          branches:
            ignore: master